Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.
  
  # number of cluster nodes
  N_NODE = 3

  # number of control-plane nodes
  N_MASTER = 1

  # cluster nodes configuration on VM provider layer 
  NODES_CONFIG = {
      :box => "centos/7",
      :cpu => 1,
      :mem => 1024,
      :name => "node-kubernetes"
  }

  # master configuration on VM provider layer
  MASTER_CONFIG = {
      :box => "centos/7",
      :cpu => 1,
      :mem => 512,
      :name => "master-kubernetes"
  }

  # chose of provider type <hyperv | virtualbox>
  PROVIDER = "hyperv"

  config.vm.provider PROVIDER
  
  if PROVIDER == "hyperv"
    config.trigger.before :up do |trigger|
      trigger.info = "Creating 'NATSwitch' Hyper-V switch if it does not exist..."
  
      trigger.run = {privileged: "true", powershell_elevated_interactive: "true", path: "./hyperv-provisioner/create-switch.ps1"}
    end
    config.vm.provider PROVIDER do |p|
      p.enable_virtualization_extensions = true
      p.linked_clone = true
    end
  end

  if PROVIDER == "virtualbox"
    config.vm.provider PROVIDER do |p|
      p.enable_virtualization_extensions = true
      p.linked_clone = true
    end
  end
  
  (1..N_MASTER).each do |i|
    config.vm.define "kube-master-#{i}" do |master|
      master.vm.box = MASTER_CONFIG[:box]
      master.vm.network "private_network", ip: "172.16.0.#{10 + i}", bridge: "NATSwitch"
      master.vm.hostname = "kubernetes-master"
      master.vm.provision "shell", path: "kube_master.sh", args: ["172.16.0.#{10 + i}"] 
      master.vm.provider PROVIDER do |master_config|
        master_config.memory = MASTER_CONFIG[:mem]
        master_config.cpus = MASTER_CONFIG[:cpu]
        master_config.vmname = "#{MASTER_CONFIG[:name]}"
      end
    end
  end

  (1..N_NODE).each do |i|
    config.vm.define "kube-node-#{i}" do |node|
      node.vm.box = NODES_CONFIG[:box]
      node.vm.network "private_network", ip: "172.16.0.#{100 + i}", bridge: "NATSwitch"
      node.vm.hostname = "kubernetes-node-#{i}"
      node.vm.provision "shell", path: "kube_node.sh", args: ["172.16.0.#{100 + i}"] 
      node.vm.provider PROVIDER do |node_config|
        node_config.memory = NODES_CONFIG[:mem]
        node_config.cpus = NODES_CONFIG[:cpu]
        node_config.vmname = "#{NODES_CONFIG[:name]}-#{i}"
      end
    end
  end

  
end
